apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: database
resources:
  - persistentVolume.yaml
  - persistentVolumeClaim.yaml
  - deployment.yaml
  - service.yaml
#patches:
#  - path: service.yaml
#  - path: deployment.yaml
#  - path: ingress.yaml