apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: "dummy_db"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "" #your password inside quotes