apiVersion: v1
kind: PersistentVolume
metadata:
  name: parquet-volume
  labels:
    type: local
    app: parquet
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /parquet