apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-volume-claim
  labels:
    app: parquet
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi